repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --manifest-path core/Cargo.toml
        language: system
        types: [rust]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^docs/
        exclude: ^docs/node_modules/
