name: Pre-commit formatting

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit (formatting pass)
        id: precommit_format
        run: |
          set +e
          pre-commit run --all-files
          status=$?
          echo "exit_code=$status" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Commit formatting changes
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore: apply pre-commit auto-formatting
          branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Run pre-commit (verification)
        run: pre-commit run --all-files
